MONGODB_HOST: mongodb-dev.abhishekdev.fun
REDIS_HOST: redis-dev.abhishekdev.fun
CATALOGUE_HOST: catalogue-dev.abhishekdev.fun
CART_HOST: cart-dev.abhishekdev.fun
USER_HOST: user-dev.abhishekdev.fun
RABBITMQ_HOST: rabbitmq-dev.abhishekdev.fun
MYSQL_HOST: mysql-dev.abhishekdev.fun
SHIPPING_HOST: shipping-dev.abhishekdev.fun
PAYMENT_HOST: payment-dev.abhishekdev.fun