MONGODB_HOST: mongodb-dev.abhishekdev.fun
REDIS_HOST: redis-dev.abhishekdev.fun
CATALOGUE_HOST: catalogue.backend-alb-dev.abhishekdev.fun
CART_HOST: cart.backend-alb-dev.abhishekdev.fun
USER_HOST: user.backend-alb-dev.abhishekdev.fun
RABBITMQ_HOST: rabbitmq-dev.abhishekdev.fun
MYSQL_HOST: mysql-dev.abhishekdev.fun
SHIPPING_HOST: shipping.backend-alb-dev.abhishekdev.fun
PAYMENT_HOST: payment.backend-alb-dev.abhishekdev.fun