MONGODB_HOST: mongodb.abhishekdev.fun
REDIS_HOST: redis.abhishekdev.fun
CATALOGUE_HOST: catalogue.abhishekdev.fun
CART_HOST: cart.abhishekdev.fun
USER_HOST: user.abhishekdev.fun
RABBITMQ_HOST: rabbitmq.abhishekdev.fun
MYSQL_HOST: mysql.abhishekdev.fun
SHIPPING_HOST: shipping.abhishekdev.fun
PAYMENT_HOST: payment.abhishekdev.fun