- name: copy {{ component }} service
  ansible.builtin.template:
    src: "catalogue.service.j2"
    dest: "/etc/systemd/system/catalogue.service"
  notify: daemon reload

- name: start the service
  ansible.builtin.service:
    name: "catalogue"
    state: restarted
    enabled: yes
