- name: copy mongodb service
  ansible.builtin.template:
    src: "mongodb.service.j2"
    dest: "/etc/systemd/system/mongodb.service"
  notify: daemon reload

- name: start the service
  ansible.builtin.service:
    name: "mongodb"
    state: restarted
    enabled: yes
